spring:
  application:
    name: "tunein"
  datasource:
    url: "jdbc:mysql://localhost:3306/tunein"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    open-in-view: "false"
