spring:
  application:
    name: "tunein"
  datasource:
    url: "jdbc:mysql://localhost:3306/tunein"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    open-in-view: "false"

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 6001

storage:
  server:
    url: "http://localhost:6002"

security:
  jwt:
    secret-key: "bc91a2dc40bc4db2c4db85f3590e011456ee2ba43d1ba5583635d7d6f25e2c70"
    expiration-time: 3600000
