spring:
  application:
    name: "tunein"
  datasource:
    url: "jdbc:mysql://localhost:3306/tunein"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    open-in-view: "false"

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 6001

storage:
  server:
    url: "http://localhost:6002"
