spring:
  application:
  name: "tunein_storage"
  datasource:
    url: "jdbc:mysql://localhost:3306/tunein_storage"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: "update"
    open-in-view: "false"
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 6002
storage:
  root: "E:\\Spring Projects\\TuneIn\\storage"
